import React from 'react';
import prisma from '@/lib/prisma';
import { getCurrentAdminUser } from '@/lib/auth/admin';
import { Badge } from '@/ui/Badge';
import { ValuationsListClient } from './ValuationsListClient';

export const dynamic = 'force-dynamic';

export default async function AdminValuationsPage() {
  const user = await getCurrentAdminUser();
  if (!user) return null;

  const valuations = await prisma.valuationRequest.findMany({
    orderBy: { createdAt: 'desc' },
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="space-y-1 border-b border-[#d8cebe]/60 pb-4">
        <div className="flex items-center gap-2">
          <Badge variant="exclusive" size="sm">Seller Valuations</Badge>
          <span className="text-xs font-mono text-[#7e7365]">
            {valuations.length} Requests Submitted
          </span>
        </div>
        <h1 className="font-display font-medium text-2xl sm:text-3xl text-[#1F1B16]">
          Property Valuation Requests
        </h1>
        <p className="text-xs text-[#7e7365]">
          Valuation requests generated by homeowners and investors via the online price calculator
        </p>
      </div>

      <ValuationsListClient
        initialValuations={valuations.map((v: any) => ({
          ...v,
          areaSize: Number(v.areaSize),
          estimatedMin: v.estimatedMin ? Number(v.estimatedMin) : null,
          estimatedMax: v.estimatedMax ? Number(v.estimatedMax) : null,
        }))}
      />
    </div>
  );
}
